version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: STRONG_PASS
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U app_user -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: ./backend
    env_file: ./backend/.env
    environment:
      DATABASE_URL: postgres://app_user:STRONG_PASS@db:5432/app_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
volumes:
  db_data:
