# fly.toml app configuration file generated for try-buy-backend on 2025-08-10T16:19:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "try-buy-backend"
primary_region = "ams"

[http_service]
  internal_port = 8080        # bez podvlake; mora biti 8080 kao integer
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]         # može ostati; nije problem

[mounts]
  source = "data"             # IME volumena MORA biti "data"
  destination = "/data"