name: Generate & Commit App
on:
  workflow_dispatch:
  push:
    paths: [".blueprints/**"]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read spec
        id: spec
        run: echo "SPEC<<EOF" >> $GITHUB_OUTPUT && cat .blueprints/spec.md >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT

      - name: Generate code (OpenAI)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo ">>> Simulacija generiranja koda iz SPEC-a"
          mkdir -p frontend backend
          echo "# Frontend placeholder" > frontend/README.md
          echo "# Backend placeholder" > backend/README.md

      - name: Commit
        run: |
          git config user.name "ai-bot"
          git config user.email "ai-bot@users.noreply.github.com"
          git add -A
          git commit -m "AI: scaffold/update" || echo "No changes"
          git push
