name: Deploy Backend to VPS

on:
  push:
    branches: [ main ]          # promijeni ako deployaš drugi branch
    paths:
      - "backend/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch: {}         # ručno pokretanje iz Actions taba

env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_PORT: ${{ secrets.SSH_PORT }}
  DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
  PM2_APP: ${{ secrets.PM2_APP }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start SSH agent with private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust VPS host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Rsync backend to VPS (keep .env on server)
        run: |
          rsync -az --delete \
            --exclude ".env" \
            --exclude "node_modules" \
            ./backend/ "$SSH_USER@$SSH_HOST:$DEPLOY_PATH/"

      - name: Install deps, Prisma, PM2 reload on VPS
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "bash -lc '
            set -e
            export NVM_DIR=\"$HOME/.nvm\"
            [ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"
            cd \"$DEPLOY_PATH\"
            node -v && npm -v || true
            command -v pm2 >/dev/null 2>&1 || npm i -g pm2
            npm ci --omit=dev || npm i --production
            if [ -f prisma/schema.prisma ]; then
              npx prisma generate --schema prisma/schema.prisma || true
              npx prisma migrate deploy --schema prisma/schema.prisma || true
            fi
            pm2 start index.js --name \"$PM2_APP\" --time --node-args=\"--env-file=.env\" || pm2 reload \"$PM2_APP\"
            pm2 save
          '"

      - name: Healthcheck backend (localhost)
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" << 'EOF'
          set -e
          echo "Probing http://127.0.0.1:8080/healthz ..."
          for i in {1..20}; do
            RESP=$(curl -fsS -m 2 http://127.0.0.1:8080/healthz || true)
            if echo "$RESP" | grep -q healthy; then
              echo "OK: $RESP"
              exit 0
            fi
            sleep 1
          done
          echo "Healthcheck FAILED. PM2 status i zadnji logovi:"
          pm2 status || true
          pm2 logs trybuy-api --lines 80 || true
          exit 1
          EOF
