name: reset-user

on:
  workflow_dispatch:
    inputs:
      email:
        description: "User email to reset"
        required: true
        type: string
      password:
        description: "New password (will be bcrypt hashed)"
        required: true
        type: string

jobs:
  reset:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}   # puna PG konekcija s ?sslmode=require

    steps:
      - name: (Optional) checkout
        uses: actions/checkout@v4

      - name: Install bcryptjs
        run: npm i -g bcryptjs

      - name: Make bcrypt hash
        id: makehash
        shell: bash
        env:
          PASS: ${{ inputs.password }}
        run: |
          set -euo pipefail
          HASH=$(node -e "import('bcryptjs').then(m=>m.hash(process.env.PASS,12).then(h=>console.log(h)))")
          echo "hash=$HASH" >> "$GITHUB_OUTPUT"

      - name: Update passwordHash in Postgres
        shell: bash
        env:
          EMAIL: ${{ inputs.email }}
          HASH: ${{ steps.makehash.outputs.hash }}
        run: |
          set -euo pipefail
          # :’VAR’ je psql literal – sigurno ubacuje vrijednost i pravilno escap-a $
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 \
            -v EMAIL="$EMAIL" -v HASH="$HASH" \
            -c 'UPDATE "User" SET "passwordHash" = :'HASH' WHERE email = :'EMAIL';'
          psql "$DATABASE_URL" -v EMAIL="$EMAIL" \
            -c 'SELECT email FROM "User" WHERE email = :'EMAIL';'
