name: reset-user

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email korisnika za reset'
        required: true
        default: 't.martinovic@mpg.hr'
      password:
        description: 'Nova lozinka'
        required: true
        default: 'superuser!123'
  push:
    paths:
      - '.github/workflows/reset-user.yml'

jobs:
  reset:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}   # puna PG konekcija s ?sslmode=require

    steps:
      - name: (Optional) checkout
        uses: actions/checkout@v4

      - name: Make bcrypt hash
        id: makehash
        shell: bash
        env:
          PASS: ${{ inputs.password }}
        run: |
          set -euo pipefail
          HASH=$(npx -y bcryptjs-cli hash "$PASS" 12)
          echo "hash=$HASH" >> "$GITHUB_OUTPUT"

      - name: Update passwordHash in Postgres
        shell: bash
        env:
          EMAIL: ${{ inputs.email }}
          HASH: ${{ steps.makehash.outputs.hash }}
        run: |
          set -euo pipefail
          # :’VAR’ je psql literal – sigurno ubacuje vrijednost i pravilno escap-a $
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 \
            -v EMAIL="$EMAIL" -v HASH="$HASH" \
            -c 'UPDATE "User" SET "passwordHash" = :'HASH' WHERE email = :'EMAIL';'
          psql "$DATABASE_URL" -v EMAIL="$EMAIL" \
            -c 'SELECT email FROM "User" WHERE email = :'EMAIL';'
