name: reset-user

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email korisnika za reset'
        required: true
        default: 't.martinovic@mpg.hr'
      password:
        description: 'Nova lozinka'
        required: true
        default: 'superuser1'
  push:
    paths:
      - '.github/workflows/reset-user.yml'

jobs:
  reset:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      # ...ostale varijable...
    steps:
      - name: (Optional) checkout
        uses: actions/checkout@v4

      - name: Make bcrypt hash
        id: makehash
        shell: bash
        env:
          PASS: ${{ inputs.password }}
        run: |
          set -euo pipefail
          HASH=$(npx -y bcryptjs-cli hash "$PASS" 12)
          echo "hash=$HASH" >> "$GITHUB_OUTPUT"

      - name: Update passwordHash in Postgres
        shell: bash
        env:
          EMAIL: ${{ inputs.email }}
          HASH: ${{ steps.makehash.outputs.hash }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PGSSLMODE: require
        run: |
          set -euo pipefail
          echo "DATABASE_URL=$DATABASE_URL"
          psql "$DATABASE_URL" -c "UPDATE \"User\" SET \"passwordHash\" = '$HASH' WHERE email = '$EMAIL';"
          psql "$DATABASE_URL" -c "SELECT email FROM \"User\" WHERE email = '$EMAIL';"
